- shell: curl -L git.io/nodebrew | perl - setup
- shell: echo "export PATH=$HOME/.nodebrew/current/bin:$PATH" >> ~/.bash_profile
- shell: bash -lc "nodebrew install-binary 8.11.1"
- shell: bash -lc "nodebrew use v8.11.1"
