---
- name: git clone/pull pyenv
  become_user: "{{ username }}"
  git: repo=https://github.com/yyuu/pyenv.git
       dest=~/.pyenv
       version=master
       accept_hostkey=yes
       force=yes
  tags:
    - crawler/register

- name: setting pyenv in PATH
  become_user: "{{ username }}"
  lineinfile:
    dest=~/.bash_profile
    state=present
    line={{ item }}
  with_items:
    - 'export PYENV_ROOT=~/.pyenv'
    - 'export PATH=$PYENV_ROOT/bin:$PATH'
    - 'eval "$(pyenv init -)"'
  tags:
    - crawler/register

- name: install pyenv
  become_user: "{{ username }}"
  shell: |
    source ~/.bash_profile
    # install python
    pyenv install {{anaconda_version}}
    pyenv rehash
    pyenv global {{anaconda_version}}
  tags:
    - crawler/register

- name: setting anaconda in PATH
  become_user: "{{ username }}"
  lineinfile:
    dest=~/.bash_profile
    state=present
    line={{ item }}
  with_items:
    - 'export PATH="$PYENV_ROOT/versions/anaconda3-4.3.0/bin/:$PATH"'
  tags:
    - crawler/register

- name: update conda
  become_user: "{{ username }}"
  shell: |
    source ~/.bash_profile
    conda update conda -y
  tags:
    - crawler/register

- shell: "bash -lc 'pip install {{ item }}'"
  become_user: "{{ username }}"
  with_items:
    - 'numpy'
    - 'sqlalchemy' # for not use PyMySQL
    - 'pillow'
    - 'PyMySQL' # only for django
    - 'cx_Oracle'
    - 'redis'
    - 'yml'
    - 'tensorflow'
    - 'keras'
    - 'selenium'
    - 'folium'
    - 'uwsgi' # for web python (django)
    - 'django'
    - 'django-debug-toolbar'
    - 'jupyter'
  tags:
    - crawler/register

- name: install python2
  become_user: "{{ username }}"
  shell: |
    source ~/.bash_profile
    conda create -n pyt2 python=2.7 anaconda
  tags:
    - crawler/register

