- name: yum install httpd packages
  yum: name=httpd state=present

- name: start httpd
  service: name=httpd state=started
  
- name: httpd.conf replace
  replace: >
    dest=/etc/httpd/conf/httpd.conf
    regexp={{ item.regexp }}
    replace={{ item.replace }}
  with_items: "{{ httpd_regexp_replace }}"

- name: setting virtualhost.conf
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src:  virtualhost.conf,  dest: /etc/httpd/conf.d/virtualhost.conf }

- name: chkconfig httpd on
  shell: chkconfig httpd on
