---
- name: install {{ project_name }} middleware
  hosts: stock_crawler
  connection: local
  become: yes
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/httpd, tags: ['httpd']}
    - {role: middleware/mysql,tags: ['mysql']}
    - {role: middleware/php,tags: ['php']}

- name: install {{ project_name }} application
  hosts: stock_crawler
  connection: local
  become: yes
  vars_files:
    - vars/cakephp.{{ _env }}.yml
  tasks:
    - name: remove default php
      shell: yum -y remove php*

    - name: install php 5.6
      shell: yum -y install epel-release
      
    - shell: curl -O http://rpms.famillecollet.com/enterprise/remi.repo
      args:
        chdir: /etc/yum.repos.d
      
    - shell: yum -y --enablerepo=remi,remi-php56 install httpd php php-common php-mysql

    - shell: setenforce 0 

#    - name: git clone/pull cakephp
#      git: repo=git://github.com/cakephp/cakephp.git
#           dest={{ git.dir }}
#           version={{ git.version }}
#           accept_hostkey=yes
#           force=yes
#
#    - name: permission
#      file: path={{ git.dir }} state=directory owner=apache group=apache mode=0777
