---
- name: construct
  hosts: crawler
  become: yes
  vars_files:
    - vars/crawler.{{ _env }}.yml
  roles:
    - {role: common/develop, tags: ['develop']}
    - {role: common/oracle, tags: ['oracle']}
    - {role: crawler/register, tags: ['register']}
