---
- name: construct
  hosts: stock_crawler
  become: yes
  vars_files:
    - vars/stock_crawler.dev.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/python, tags: ['python']}
    - {role: middleware/php,tags: ['php']}
    - {role: middleware/ruby,tags: ['ruby']}
    - {role: middleware/java,tags: ['java']}
    - {role: middleware/c,tags: ['c']}
    - {role: middleware/casperjs,tags: ['casperjs']}
    - {role: middleware/oracle, tags: ['oracle']}
    - {role: middleware/elastic,tags: ['elastic']}
    - {role: middleware/elastic_docker,tags: ['elastic_docker']}
