---
- name: construct
  hosts: crawler
  become: yes
  vars_files:
    - vars/crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/develop, tags: ['develop']}
    - {role: middleware/oracle, tags: ['oracle']}
    - {role: middleware/python, tags: ['python']}
    - {role: middleware/php,tags: ['php']}
    - {role: middleware/php,tags: ['ruby']}
    - {role: middleware/java,tags: ['java']}
    - {role: middleware/java,tags: ['c']}
    - {role: middleware/casperjs,tags: ['casperjs']}
    - {role: middleware/elastic,tags: ['elastic']}
