---
- name: install middleware
  hosts: localhost
  connection: local
  become: yes
  become_user: "root"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/nginx,tags: ['nginx']}
    - {role: middleware/nodejs,tags: ['nodejs']}
    - {role: middleware/mysql,tags: ['mysql']}
    - {role: middleware/ruby,tags: ['ruby']}

  hosts: localhost
  connection: local
  become: yes
  become_user: "vcp"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  tasks:
    - name: set ruby
      shell: echo 'export PATH=\"/usr/local/rbenv/bin:$PATH\"' >> /home/vcp/.bash_profile

    - name: set rbenv env file2
      when: not fm.stat.exists
      shell: echo 'eval "$(rbenv init -)"' >> /home/vcp/.bash_profile

    - name: install2 ruby-build
      shell: sh {{ rbenv_root }}/plugins/ruby-build/install.sh

    - name: install ruby with rbenv
      when: not fm.stat.exists
      shell: bash -lc "source /home/vcp/.bash_profile; CONFIGURE_OPTS="--disable-install-rdoc" rbenv install {{ ruby_version }}"

    - name: "set ruby {{ ruby_version }} for system"
      shell: bash -lc "source /home/vcp/.bash_profile; rbenv global {{ ruby_version }} && rbenv rehash"

    - name: "install bundler"
      shell: bash -lc "rbenv exec gem install bundler"

- name: install middleware
  hosts: localhost
  connection: local
  become: yes
  become_user: "vcp"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  tasks:
    - shell: bash -lc "gem install rails"
    - shell: echo "export RAILS_DATABASE_USER="rails_user"" >>  ~/.bash_profile
    - shell: echo "export RAILS_DATABASE_PASSWORD="g4s3WjdrgsrB8Kb$"" >>  ~/.bash_profile
    - shell: echo "export RAILS_ENV="development"" >>  ~/.bash_profile
    - shell: bash -lc "source ~/.bash_profile"
