---
- name: install middleware
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/nginx,tags: ['nginx']}
    - {role: middleware/nodejs,tags: ['nodejs']}
    - {role: middleware/mysql,tags: ['mysql']}
    - {role: middleware/ruby,tags: ['ruby']}

- shell: bash -lc "gem install rails"

- shell: echo "export RAILS_API_DATABASE_USER="root"" >>  ~/.bash_profile
- shell: echo "export RAILS_API_DATABASE_PASSWORD="admin"" >>  ~/.bash_profile
- shell: echo "export RAILS_ENV="development"" >>  ~/.bash_profile
- shell: bash -lc "source ~/.bash_profile"
