---
- name: install middleware
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/nginx,tags: ['nginx']}
    - {role: middleware/nodejs,tags: ['nodejs']}
    - {role: middleware/mysql,tags: ['mysql']}
    - {role: middleware/ruby,tags: ['ruby']}

- name: install middleware
  hosts: localhost
  connection: local
  become: yes
  become_user: "vcp"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  tasks:
    - shell: bash -lc "source /home/vcp/.bash_profile; gem install rails"
    - shell: echo "export RAILS_DATABASE_USER="rails_user"" >>  /home/vcp/.bash_profile 
    - shell: echo "export RAILS_DATABASE_PASSWORD="g4s3WjdrgsrB8Kb$"" >>  /home/vcp/.bash_profile 
    - shell: echo "export RAILS_ENV="development"" >>  /home/vcp/.bash_profile 
    - shell: bash -lc "source /home/vcp/.bash_profile "
