---
- name: install middleware
  hosts: localhost
  connection: local
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/nginx,tags: ['nginx']}
    - {role: middleware/nodejs,tags: ['nodejs']}
    - {role: middleware/mysql,tags: ['mysql']}
    - {role: middleware/ruby,tags: ['ruby']}

- name: install middleware
  hosts: localhost
  connection: local
  become: yes
  become_user: "vcp"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  tasks:
    - become_user: "{{ username }}"
      shell: |
        source ~/.bash_profile
        gem install rails
    - become_user: "{{ username }}"
      lineinfile:
        dest=~/.bash_profile
        state=present
        line={{ item }}
      with_items:
        - 'export RAILS_DATABASE_USER="rails_user"'
        - 'export RAILS_DATABASE_PASSWORD="g4s3WjdrgsrB8Kb$"'
        - 'export RAILS_ENV="development"'
