---
- name: install {{ project_name }} middleware
  hosts: stock_crawler
  become: yes
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: middleware/common,tags: ['common']}
    - {role: middleware/python, tags: ['python']}
    - {role: middleware/elastic,tags: ['elastic']}

- name: vault key on localhost
  hosts: localhost
  become: yes
  become_user: "{{ username }}"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: application/common/vault_key, tags: ['vault_key']}

- name: install {{ project_name }} application
  hosts: stock_crawler
  become: yes
  become_user: "{{ username }}"
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: application/common/git_clone_pull, tags: ['pull']}
    - {role: application/stock_crawler, tags: ['crawler']}
    - {role: application/common/cythonize, tags: ['cythonize']}

- name: install {{ project_name }} logrotate
  hosts: stock_crawler
  become: yes
  vars_files:
    - vars/stock_crawler.{{ _env }}.yml
  roles:
    - {role: application/common/logrotate,tags: ['logrotate']}
