---
- name: git clone/pull key
  become_user: "{{ username }}"
  git: repo=git@github.com:katsudonik/auth.git
       key_file=~/.ssh/id_rsa
       dest=~/.auth
       version=master
       accept_hostkey=yes
       force=yes
  tags:
    - git_clone_pull

- name: link
  file: src=~/.auth dest={{ role_path }}/templates owner={{ username }} group={{ username }} state=link

- name: decrypt
  shell: ansible-vault decrypt {{ role_path }}/templates/{{ git.key }} --vault-password-file {{ vault_password_path }}

- name: prepare deploy key for {{ project_name }}
  become_user: "{{ username }}"
  template: >
    src={{ git.key }}
    dest=~/.ssh/{{ git.key }}
    mode=0600
  tags:
    - git_clone_pull
