- name: yum install nginx
  yum: name=nginx state=present enablerepo=nginx

- name: default.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  
- name: systemctl enable nginx.service
  shell: systemctl enable nginx.service
