- name: set nginx.repo
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: yum install nginx
  yum: name=nginx state=present enablerepo=nginx
  tags:
    - nginx

- name: default.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  tags:
    - nginx
  
- name: systemctl enable nginx.service
  shell: systemctl enable nginx.service
  tags:
    - nginx
