---
- name: setting logrotate to /etc/logrotate.d/{{ project_name }}
  become: yes
  become_user: "{{ username }}"
  template: >
    src={{ item. src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0644
  with_items:
    - { src: "logrotate", dest: "/etc/logrotate.d/{{ project_name }}" }
  tags:
    - stock_crawler
