# 転送
- name: copy to host "/tmp/{{ item }}"
  copy: src={{ item }} dest=/tmp/{{ item }}

# RPMインストール
- name: install "{{ item}}"
  shell: rpm -ivh /tmp/{{ item }}

# 削除
- name: remove "/tmp/{{ item }}"
  file: path=/tmp/{{ item }} state=absent
