---
- name: create log directory
  become_user: "{{ username }}"
  file: >
    path=~/spider_register/{{ item }}
    state=directory
    owner={{ username }}
    group={{ username }}
    mode=0755
  with_items:
    - {{ config_dir }}
  tags:
    - stock_crawler

- name: application config
  become: yes
  become_user: "{{ username }}"
  template: >
    src={{ item. src }}
    dest=~/spider_register/config/{{ item.dest }}
    mode=0755
  with_items:
    - { src: "stock_crawler.{{ _env }}.yml", dest: register.yml }
    - { src: "logging.{{ _env }}.ini", dest: logging.ini }
  tags:
    - crawler/register

- name: setting logrotate to /etc/logrotate.d/{{ project_name }}
  template: >
    src={{ item. src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0644
  with_items:
    - { src: "logrotate", dest: "/etc/logrotate.d/{{ project_name }}" }
  tags:
    - stock_crawler
