version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata3:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    links:
        - elasticsearch1
    ports:
        - 5601:5601
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch1:9200
    depends_on:
      - "elasticsearch1"

#  logstash:
#    image: docker.elastic.co/logstash/logstash:5.5.2
#    links:
#       - elasticsearch1
#    networks:
#      - esnet
#    volumes:
#      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./ojdbc8.jar:/usr/share/logstash/bin/ojdbc8.jar
#      - ./t_ad_crawl_result.conf:/usr/share/logstash/pipeline/t_ad_crawl_result.conf
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch1:9200
#      - ELASTICSEARCH_DOMAIN=elasticsearch1
#    depends_on:
#      - "elasticsearch1"
#    command: /usr/share/logstash/bin/logstash-plugin install x-pack

  offer_search:
    build: ./offer_search
    links:
        - elasticsearch1
    ports:
        - 8080:8080
    networks:
      - esnet
    stdin_open: true
    tty: true

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet:
