- name: yum remove
  yum: name=mariadb-libs state=removed

- file: path=/var/lib/mysql state=absent

- file: path=/var/log/mysqld.log state=absent

- shell: yum localinstall http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm

- name: yum install mysqld packages
  yum: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name:  mysql-community-server,  state: present }

- name: setting my.cnf
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src:  my.cnf,  dest: /etc/my.cnf }

- name: start mysqld
  service: name=mysqld state=started
