---
- name: prepare deploy key for {{ project_name }}
  become_user: "{{ username }}"
  template: >
    src={{ git.key }}
    dest=~/.ssh/{{ git.key }}
    mode=0600
  tags:
    - git_clone_pull

- name: git clone/pull {{ project_name }}
  become_user: "{{ username }}"
  git: repo=git@{{ git.domain }}:{{ git.user }}/{{ git.repository_name }}.git
       key_file={{ git.key_path }}
       dest={{ git.dir }}
       version={{ git.version }}
       accept_hostkey=yes
       force=yes
  tags:
    - git_clone_pull

- name: Change directory permission.{{ git.mode }}
  become_user: "{{ username }}"
  file:  >
    path={{ git.dir }}
    owner={{ git.owner }}
    group={{ git.group }}
    mode={{ git.mode }}
    state=directory
    recurse=yes
  tags:
    - stock_crawler
