---
# centos7

- name: install packages
  yum: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name: tar,            state: present }
    - { name: make,           state: present }
    - { name: libffi-devel,   state: present }
    - { name: zlib-devel,     state: present }
    - { name: openssl-devel,  state: present }
    - { name: gcc,            state: present }
    - { name: readline-devel, state: present }
    - { name: bzip2,          state: present }
    - { name: ruby,           state: present }
    
  tags:
    - ruby

- name: install rbenv
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ rbenv_root }}
  tags:
    - ruby

- name: install ruby-build
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build
  tags:
    - ruby

- name: create rbenv group
  group: name=rbenv state=present
  tags:
    - ruby

- name: add rbenv user to rbenv group
  user: name={{ rbenv_user }} append=yes groups=rbenv
  register: add_group
  tags:
    - ruby

- name: create dirs
  file: path={{ rbenv_root }}/{{ item.name }} state=directory
  with_items:
    - { name: shims }
    - { name: versions }
  tags:
    - ruby

- name: change owner of install dir
  file: path={{ rbenv_root }} group=rbenv mode=2775 state=directory recurse=yes
  when: not fm.stat.exists
  tags:
    - ruby

- name: set rbenv env file
  copy: src=rbenv.sh dest=/etc/profile.d mode=0775
  tags:
    - ruby

- name: setting rbenv in PATH
  become_user: "{{ rbenv_user }}"
  lineinfile:
    dest=~/.bash_profile
    state=present
    line={{ item }}
  with_items:
    - 'export RBENV_ROOT={{ rbenv_root }}'
    - 'export PATH=$RBENV_ROOT/bin:$PATH'
    - 'eval "$(rbenv init -)"'
  tags:
    - ruby

- name: install ruby-build
  become_user: "{{ rbenv_user }}"
  shell: |
    source ~/.bash_profile
    sh {{ rbenv_root }}/plugins/ruby-build/install.sh
  tags:
    - ruby
    
- name: install2 ruby-build
  shell: sh {{ rbenv_root }}/plugins/ruby-build/install.sh

- name: install ruby
  become_user: "{{ rbenv_user }}"
  shell: |
    source ~/.bash_profile
    # install ruby
    rbenv install {{ ruby_version }}
    rbenv global {{ ruby_version }}
    rbenv rehash
    rbenv exec gem install bundler
    gem install rails
  tags:
    - ruby
    
- name: setting rails
  become_user: "{{ rbenv_user }}"
  lineinfile:
    dest=~/.bash_profile
    state=present
    line={{ item }}
  with_items:
    - 'export RAILS_DATABASE_USER="rails_user"'
    - 'export RAILS_DATABASE_PASSWORD="g4s3WjdrgsrB8Kb$"'
    - 'export RAILS_ENV="development"'
  tags:
    - ruby
