- shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: yum kibana repogitory
  template: src=kibana.repo dest=/etc/yum.repos.d/kibana.repo

- name: install java8/Elasticsearch/kibana/logstash
  yum: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name:  net-tools,  state: present }
    - { name:  java-1.8.0-openjdk-devel,  state: present }
    - { name:  'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.rpm',  state: present }
    - { name:  kibana,  state: present }
    - { name:  logstash,  state: present }

- shell: java -version

- name: setting elasticsearch/kibana
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src:  elasticsearch.yml,  dest: /etc/elasticsearch/elasticsearch.yml }
    - { src:  kibana.yml,  dest: /etc/kibana/kibana.yml }

- elasticsearch_plugin:
    plugin_bin: /usr/share/elasticsearch/bin/elasticsearch-plugin
    timeout: null
    state: present
    name: analysis-kuromoji

- name: Change logstash directory permission.
  file: path=/usr/share/logstash/data owner=logstash group=logstash mode=0777 state=directory recurse=yes

- name: set logstash conf
  template: src={{ item.src }} dest=/etc/logstash/conf.d/{{ item.dest }}
  with_items:
    - { src:  t_ad_crawl_result.conf,  dest: t_ad_crawl_result.conf }
    - { src:  t_ad_crawl_result_ad.conf,  dest: t_ad_crawl_result_ad.conf }
    - { src:  t_ad_crawl_result_detail.conf,  dest: t_ad_crawl_result_detail.conf }

- shell: systemctl stop firewalld

#-shell: /etc/init.d/elasticsearch start

#-shell: /etc/init.d/kibana start

#- name: set jdbc driver
#  template: src=ojdbc8.jar dest=/usr/share/logstash/bin/ojdbc8.jar

#-shell: service logstash start

