---
- name: cythonize
  become_user: "{{ username }}"
  shell: mv {{ file_name }}.py {{ file_name }}.pyx
  args:
    chdir: "{{ src_dir }}"
  tags:
    - stock_crawler

- name: compile
  become_user: "{{ username }}"
  shell: |
    source ~/.bash_profile
    /home/vcp/.pyenv/versions/anaconda3-4.3.0/bin/python setup.py {{ item }}
  args:
    chdir: "{{ src_dir }}"
  with_items:
    - 'build_ext'
    - 'install_lib'
  tags:
    - stock_crawler